### ISSUE TITLE
remove_silent_frames() modifies input even if no frames are silent

### ISSUE THREAD

**Issue by Rikorose** [mpariente/pystoi#17]
So I think there are 3 issues that I spotted.

1. You don't divide by `sqrt(N)` like here
https://github.com/mpariente/pystoi/blob/master/tests/matlab/stoi.m#L158
Though I am not sure why `sqrt(N)` is correct and not something window dependent like `sqrt(sum(window))`.

2. You don't divide by the window during overlap add. Since you multiplied the input with the window [here](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L119), to preserve energy you need to divide by `w` probably [here](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L140).

3. The output dimensions are not preserved, i.e. the output is shorter than the input. I think this can be solved via padding at the start and cropping afterwards similar to this:
```py
orig_len = x.shape[1]
pad = framelen - orig_len % framelen
pad_front, mod = divmod(pad, 2)
pad_end = pad_front + mod
x_padded = np.pad(x, (pad_front, pad_end))

# ...

# Check if the first frame was kept
if mask[0]:  # mask is true if frame is *not* silent and we keep it
    # then there will be the 0-padding in the beginning of length pad_front
    x_sil = x_sil[pad_fron:]
    y_sil = y_sil[pad_fron:]
# Cut the remaining if the last frame was kept
if mask[-1]:
    x_sil = x_sil[-pad_end:]
    y_sil = y_sil[-pad_end:]
```

I think a test would be good that tests if the input is equal (or close) to the output given a loud enough signal.

**Comment by mpariente** [comment]
Thank you @Rikorose for thoroughly reviewing the code. 

 
> You don't divide by `sqrt(N)` like here
> https://github.com/mpariente/pystoi/blob/master/tests/matlab/stoi.m#L158
>  Though I am not sure why `sqrt(N)` is correct and not something window dependent like `sqrt(sum(window))`.
> 

The normalization constant inside the log actually doesn't matter because we take a difference of energies [here](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L128) and it is used nowhere else.

> You don't divide by the window during overlap add. Since you multiplied the input with the window [here](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L119), to preserve energy you need to divide by `w` probably [here](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L140).
> 
`w` is a hanning window, so that overlap-add is almost constant for an overlap of 50%, you can try this :
```python
from pystoi.utils import remove_silent_frames
import numpy as np
import matplotlib.pyplot as plt

x = y = np.ones((32000,))
u, v = remove_silent_frames(x, y, 40, 256, 128)
plt.plot(u)
plt.show()
```
It shows that the energy is indeed conserved and shows the precision of the OLA. 

> The output dimensions are not preserved, i.e. the output is shorter than the input.
> 

I agree with this remark but I can't change it.


This repo is about reproducing a metric which has already been designed in MATLAB. In the original code, the input dimensions are not preserved either, I'm not the author of the metric, I have no right to modify it. Sorry about that.

**Comment by Rikorose** [comment]
Alright, thanks for the clarification!
