### ISSUE TITLE
remove_silent_frames

### ISSUE THREAD

**Issue by gauss256** [mpariente/pystoi#4]
I think the way the signal is being reconstructed in `remove_silent_frames` is not quite right. The evidence for this is that if you start with a signal that has no silence, the output of `remove_silent_frames` should be the same as the input, but it's not. 

The problem is that the window does not satisfy the COLA constraint so the overlap-add technique needs to be modified to compensate.

I know how to fix this but I wanted to get your opinion before preparing a PR. The issue is that the problem lies in the original STOI MATLAB code, not in `pystoi`. So if it is fixed, tests that compare to the output of MATLAB will fail.

The magnitude of the error is probably not large, so it's a tradeoff. Is it better to have correct silence removal or consistency with MATLAB output?

**Comment by mpariente** [comment]
Thanks for this remark. 
For a signal with no silence, the output of the method will be equal to the input up to a multiplicative factor (the scaling factor of the OLA) right? 
If this is the only difference, I don't see the problem because everything is normalized afterwards so the final result should be the same. @chtaal any thoughts on this potential problem? 

And indeed, I'd rather have consistency with MATLAB's output given that there are many papers who used the code provided by Cees Taal to produce their results and these shouldn't be different if they use the MATLAB or the Python version.
You're right to ask before writing a PR, if it would be a big mistake, we could fix it, but this looks ok to me.

**Comment by gauss256** [comment]
1. It's more than just a scaling factor, the normalization is different for every point. Also, there are some boundary effects that need to be taken care of. [This notebook](https://nbviewer.jupyter.org/urls/gauss256.github.io/blog/eda_ola_td.ipynb) illustrates the situation for the same parameters as used in STOI. It shows that the normalization values vary by almost 2x across the length of the signal.

2. I have a WIP [blog post](https://gauss256.github.io/blog/cola.html) that shows how to correctly invert a windowed time series.

3. I have not yet experimented with how big an impact this has on STOI. Probably not huge (but the results in that notebook above are a bit alarming). I'm sensitive to the issue because of a PR I'm working for SciPy (as mentioned in the blog post).

**Comment by gauss256** [comment]
I have implemented a version of `remove_silent_frames` that perfectly reproduces the input signal when there is no silence. In comparison, the current code results in an output signal that is about 5% different from the input.

Running both versions end-to-end on a single test file results in STOI values that differ by about 1%. This is small enough that we could just ignore it, although more comprehensive testing would be nice.

An alternative: we could offer it as an option and keep the current version as a "compatibility mode" option.

**Comment by mpariente** [comment]
Thanks for the input. 
I already saw this [kind of implementation](https://stackoverflow.com/questions/2459295/invertible-stft-and-istft-in-python) of the OLA in SO. But indeed the padding/boundary is a good addition to this method.

About the error of the STOI, Is this error systematic? Could you give me the distribution? Because if it is systematic, then it's not a problem. 

My habit is to use a hop size which is 4 times smaller than the FFT size, so the sum of my shifted squared windows is constant. 
The problem with N=2 (overlap of 50%) is that shifted windows don't add up to a constant. Dividing by this squared sum is working when we don't change the frames of the STFT, you can guaranty that the reconstruction is perfect. 
But as the squared sum of the shifted windows is not a constant for N=2, when you change the frames, you cannot guaranty that you don't introduce artefacts. So for a good reconstruction, we still need the squared sum to be a constant. 

I think this method is nice for perfect reconstruction of an unchanged signal. But some tests have to be performed to evaluate how much artefacts are introduced when the signal is changed in the frequency domain, and compare it to the classical OLA method. 

@chtaal : any thoughts on this?

**Comment by gauss256** [comment]
> Is this error systematic?

If you mean, is it the same or even predictable across different inputs, then no, not really. The error will depend on how much silence there is and how it is distributed in time along the signal.

**Comment by gauss256** [comment]
> a hop size which is 4 times smaller than the FFT size, so the sum of my shifted squared windows is constant.

I don't think that such a hop size will guarantee a constant sum. Do you have a reference for that?

Here's a quick experiment I did with Hann window, FFT size = 64, and hop size = 16. Even ignoring the boundary effects there is a noticeable variation in the sum-of-squares values.

![quarter_hop](https://user-images.githubusercontent.com/9168281/40578631-2473881e-60cc-11e8-99f6-c62d2238c5da.png)

**Comment by mpariente** [comment]
Actually, the definition of the hanning window in this way `hanning(N+2)[1:-1]` is more used for filter design than for STFT. 
For STFT, we prefer the periodic definition of the window `hanning(N)[:-1]`.
Could you try with this definition please? It should sum up to a constant in this case.

Probably, the silent frame removal could have been done in a better way, I do agree with you. But maybe, what is more important than the complete correctness of the method is the fact that it correlates well with psychophysical experiments

**Comment by gauss256** [comment]
With window `hanning(N+1)[:-1]` the sums are constant, because that window satisfies COLA. For the sums to be constant everywhere, you do need to zero-pad the signal at each end by a full frame. No such padding is done in the STOI code. Without that padding, the sums look like this:

![cola_no_padding](https://user-images.githubusercontent.com/9168281/40589951-9c1f2f14-61ab-11e8-9b02-e287bbf9f7db.png)

With padding, you get:

![cola_with_padding](https://user-images.githubusercontent.com/9168281/40590001-86cb02ea-61ac-11e8-98e8-d13ffc2e0cc5.png)

For a signal of reasonable length, the difference will be minor and is unlikely to affect the ability of STOI to correlate monotonically with perceived quality. I'm being careful though because I plan to reconfigure the STOI calculation for my application and want to be sure I'm starting on solid ground.

**Comment by mpariente** [comment]
I agree with you that the first and last frames of the resynthesis with OLA are not perfect because we don't use padding. 

But iff you use padding in `remove_silent_frames`, the first frame will be silence so it won't be added and the second one (if using 50% overlap) will likely be considered as silence as it will be twice less powerful (half of the values are zeros) and it seems we are back to the original problem.

My idea is that the OLA method you suggest looks good on an example without any modifications to the spectrogram but we have no guaranty that it will work better than the classic OLA when you modify the frames.

**Comment by mpariente** [comment]
Ok, I think I found a way to decide whether I want to use the method you suggest in general, not only in STOI. 
I use OLA mainly to reconstruct signals which were masked in the frequency domain (with IBM or IRM). 
If we can show that the reconstruction SDR is better for your method than for the classic OLA, I'm ready to use it. 
And by better SDR, I mean that it's distribution has higher mean and lower or equal variance. 

I won't have the time to look into this right now, but I will probably later. If you experiment with this idea, I'm really interested in the results!

**Comment by gauss256** [comment]
Just to be clear, if you normalize then you don't need to pad.

I too am mostly interested in reconstructing an audio signal from a masked spectrogram. The standard way to do that (e.g., the `istft` function is `scipy.signal`) uses the Griffin-Lim formula where you normalize by sums of the square mask values. This gives a perfect reconstruction for an unmodified spectrogram and is equivalent to what I am proposing in the time domain.

So if you believe in  Griffin-Lim, you kind of have to agree with what I am suggesting! :) A gentle reminder that this is all discussed and proven in the blog post [here](https://gauss256.github.io/blog/cola.html).

To look at this all a different way, most of the STOI processing is done in the frequency domain and I would rather do the silence removal there too. Right now we apply the STFT immediately after removing silence in the time domain. I'm looking at doing the STFT first, then silence removal, then the rest of the processing. Thanks to Parseval's Theorem this should be equivalent, but there may be some issues at a detailed level. I'm working through that now.

**Comment by mpariente** [comment]
I'm only familiar with the iterative Griffin-Lim algortihm, is it what you are tatlking about? 
In this case, I don't see the equivalence. And if not, which formula did you mention? 

I read the blog post in detail, and I'm still thinking the same : If you do modify the frames, we don't know what happens.. In the case of COLA, your method would work as good but doesn't provide much benefit because you also divide by a constant. But in the non-COLA case, we have to make tests!

I completely agree with you for the STOI, it would be great to do everything in the frequency domain and Parseval's theorem indeed would work as we are staying at the frame level to remove the silent frames.

**Comment by gauss256** [comment]
In the [original Griffin-Lim paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.306.7858&rep=rep1&type=pdf) they handle two cases:

1. When you know the phase. This is equation (6) and is the formula implemented by all ISTFT algorithms that I know of.

2. If you just have a magnitude spectrogram, then then describe their iterative approach.

Re modified frames: It's true we don't know what happens. But surely we want an algorithm that gives exact invertibility in the limiting case where the frames aren't modified. I guess you're saying that among all possible window/overlap choices, COLA windows may always work better for modified frames than non-COLA windows. I don't see why that is to be expected. Having a broader choice of window configurations seems helpful.

**Comment by mpariente** [comment]
Thanks for the references, I should really read this paper in detail some day! 

I made some small tests on the method you suggest, both with IBM and IRM and indeed the reconstruction SDR in slightly higher (between 0.05 and 0.1 dB) for the normalized OLA you suggest. 
I'll upload a gist on this when I have time, after more extensive testing with real speech and different types of windows.
