### ISSUE TITLE
Missing code for third-octave calculation

### ISSUE THREAD

**Issue by gauss256** [mpariente/pystoi#7]
In `thirdoct.m`, there is a bit of code that is not mirrored in the `pystoi` implementation. Can you clarify why it was left out?
```matlab
rnk         = sum(A, 2);
numBands    = find((rnk(2:end)>=rnk(1:(end-1))) & (rnk(2:end)~=0)~=0, 1, 'last' )+1;
A           = A(1:numBands, :);
cf          = cf(1:numBands);
```

**Comment by mpariente** [comment]
Because it basically does nothing with these values of `J` and `mn`. 
Probably it was a precaution not to include bands filled with zeros when `numbands` was too large or something. 
If the dimension of A would really be changed, the code wouldn't compile because the dimensions in this part wouldn't match :
```
x_hat = stdft(x, N_frame, N_frame/2, K);
x_hat = x_hat(:, 1:(K/2+1)).';
X = zeros(J, size(x_hat, 2));
X(:, i) = sqrt(H*abs(x_hat(:, i)).^2);
```

**Comment by gauss256** [comment]
I was looking at it because I'm generalizing the code to work with sample rates other than 10 kHz, without resampling the signal. The "missing code" is mostly sanity check stuff, true, but it did help me find some issues as I went along.

Anyway, not too important, I was just curious.
